### ISSUE TITLE
The notification platform is unavailable. (Exception from HRESULT: 0x803E0105)

### ISSUE THREAD

**Issue by PaulFreund** [PaulFreund/Chat#11]
``` bash
at Windows.UI.Notifications.BadgeUpdateManager.CreateBadgeUpdaterForApplication()
   at Backend.Common.Notifier..ctor(Runtime backend)
   at Backend.Runtime.Init()
   at Backend.Runtime..ctor()
   at Backend.Runtime.get_Instance()
   at Chat.App..ctor()
```

**Comment by abjagtap** [comment]
@PaulFreund found any solution?

**Comment by PaulFreund** [comment]
@abjagtap sorry I don't maintain this project anymore and don't have enouth time to investigate

**Comment by kristianpinke** [comment]
Hey,
I came through this because of the same error. However, I do not use your solution and I am experiencing this exception in another app.

@abjagtap Maybe it will guide you in the right direction (if not already solved) that this exception is related to the Toast Notification sub-system in Windows.
There is a difference in creating toast notifications in the classic Win32 app and UWP (Modern) app.
Here are some SO post: https://stackoverflow.com/questions/51374101/toast-notifications-in-win-forms-net-4-5
From there you can find the link for the official MS documentation where the above mention differences are described in detail.
